<?php
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<?php /** @var \Umc\Base\Block\Adminhtml\Attribute $block */ ?>
<?php $_id = $block->getEntityId().'_'.$block->getIncrement();?>
<?php $_attribute = $block->getAttributeInstance();?>
<?php if ($block->getIsTemplate()) : ?>
<script id="attribute-template" type="text/x-magento-template">
<?php endif;?>
    <div class="entry-edit umc-attribute"
         id="attribute_<?php echo $block->escapeHtml($block->getEntityId())?>_<?php echo $block->escapeHtml($block->getIncrement()); ?>">
        <div id="attribute-<?php echo $block->escapeHtml($block->getEntityId())?>-<?php echo $block->escapeHtml($block->getIncrement()); ?>-wrapper"
             class="left-collapsible-fieldset fieldset-wrapper admin__collapsible-block-wrapper opened">
            <div class="fieldset-wrapper-title">
                <strong
                    class="admin__collapsible-title"
                    data-toggle="collapse"
                    data-target="#attribute-<?php echo $block->escapeHtml($block->getEntityId())?>-<?php echo $block->escapeHtml($block->getIncrement()); ?>-content">
                    <span class="attribute-title">
                        <?php echo ($block->getAttributeInstance())
                            ? $block->escapeHtml($block->getAttributeInstance()->getLabel())
                            : $block->escapeHtml(__('Attribute %1', $block->getIncrement()));?>
                    </span>
                </strong>
                <div class="actions">
                    <button type="button" title="<?php echo $block->escapeHtml(__('Remove attribute')); ?>"
                            class="action-delete remove-attribute">
                        <span><?php echo $block->escapeHtml(__('Remove attribute')) ?></span>
                    </button>
                </div>
                <div id="attribute-<?php echo $block->escapeHtml($block->getEntityId());?>-<?php echo $block->escapeHtml($block->getIncrement()); ?>-move"
                     data-role="draggable-handle"
                     class="draggable-handle"
                     title="<?php echo $block->escapeHtml(__('Sort Attributes')); ?>">
                 </div>
            </div>
            <div id="attribute-<?php echo $block->escapeHtml($block->getEntityId());?>-<?php echo $block->escapeHtml($block->getIncrement()); ?>-content"
                 class="fieldset-wrapper-content in collapse">
                <fieldset class="fieldset">
                    <?php echo $block->getFormHtml();?>
                </fieldset>
            </div>
        </div>
    </div>
<?php if ($block->getIsTemplate()) : ?>
</script>
<?php endif;
