<?php
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<?php /** @var \Umc\Base\Block\Adminhtml\Module\Edit $block */ ?>
<?php echo $block->getFormHtml();?>
<script type="text/javascript">
    require([
        "jquery",
        "jquery/ui",
        "mage/translate",
        'mage/backend/form',
        'mage/backend/validation',
        "Umc_Base/js/umc"
    ], function(jQuery){
        jQuery(document).ready(function(){
            jQuery('#edit_form').umcmodule({
                attributeDepends: <?php /* @escapeNotVerified */  echo $block->getAttributeDepends(); ?>,
                entityDepends: <?php /* @escapeNotVerified */  echo $block->getEntityDepends(); ?>,
                relationDepends: <?php /* @escapeNotVerified */  echo $block->getRelationDepends(); ?>,
                moduleDepends: <?php /* @escapeNotVerified */  echo $block->getModuleDepends(); ?>,
                nameAttributes:<?php /* @escapeNotVerified */  echo $block->getNameAttributes(); ?>,
                relationValues: <?php /* @escapeNotVerified */  echo $block->getRelationsAsJson(); ?>,
                tooltipType: '<?php /* @escapeNotVerified */  echo $block->getTooltipType(); ?>'
            })
            .validation({
                validationUrl: '<?php /* @escapeNotVerified */  echo $block->getValidationUrl() ?>',
                highlight: function(element) {
                    jQuery(element).parents('.fieldset-wrapper-content').each(function(){
                        if (!jQuery(this).hasClass('in')) {
                            jQuery(this).prev().find('[data-toggle="collapse"]').trigger('click');
                        }
                    });
                }
            });
        });
    });

</script>
