<?php
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<?php /** @var \Umc\Base\Block\Adminhtml\Module\Edit\Tab\Entities $block */ ?>
<?php $_entities = $this->getEntities();?>
<div id="entities_container" class="left-collapsible-fieldset">
    <?php $_increment = 0;foreach ($_entities as $_code => $_entity) : ?>
        <?php
        $entityBlock = $block->getEntityBlock($_increment++, $_entity);
        echo $entityBlock->toHtml();
        ?>
    <?php endforeach;?>
</div>
