<?php
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_UMC2.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright 2015 Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<div class="fieldset-wrapper collapsable-wrapper opened">
    <div class="fieldset-wrapper-title">
        <strong class="title active" data-toggle="collapse" data-target="#umc-relations">
            <span class="entity-title"><?php echo __('Entity Relations')?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="umc-relations">
        <div id="umc-relation-container"></div>
    </div>
</div>
