<?php
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<?php /** @var \Umc\Base\Block\Adminhtml\Module\Edit\Tab\Relations $block */ ?>
<?php $_relations = $block->getRelations();?>
<div id="relations_container" class="left-collapsible-fieldset">
    <?php $_increment = 0;foreach ($_relations as $_code => $_relation) : ?>
        <?php
        /** @var \Umc\Base\Block\Adminhtml\Relation $relationBlock */
        $relationBlock = $block->getRelationBlock($_increment++, $_relation);
        echo $relationBlock->toHtml();
        ?>
    <?php endforeach;?>
</div>
