<?php
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright 2015 Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<?php /** @var \Umc\Base\Block\Adminhtml\Tooltips $this */?>
<div style="display:none" id="tooltips">
    <?php foreach ($this->getTooltips() as $tooltip) : ?>
        <div id="<?php echo $tooltip->getId();?>" title="<?php echo $tooltip->getTitle();?>" class="umc-tooltip">
            <div>
                <?php echo $tooltip->getMessage()?>
            </div>
        </div>
    <?php endforeach;?>
</div>
